### ISSUE TITLE
White-spaces in write_fasta output

### ISSUE THREAD

**Issue by kenscripts** [fkeck/bioseq#16]
When I use the write_fasta function the output fasta file contains a white-space every 10 bp in the sequence. Is there an option to not have these white-spaces in the output?

**Comment by fkeck** [comment]
Yes, please check the help of write_fasta.
The block_length argument can be used to avoid block separation by using the same value as line_length or Inf.

**Comment by kenscripts** [comment]
Hi Francis,

I see the function parameters ("block_length_argument" and "line_length" in the source code here on Github but the bioseq package (v0.1.3) I have installed does not have those parameters available for the write_fasta function. 

This is what I get when I type write_fasta in R by itself:
> write_fasta
function (x, file, append = FALSE) 
{
    x_nchar <- stringr::str_length(x)
    x_is_na <- is.na(x)
    if (any(x_is_na | x_nchar == 0L)) {
        input_len <- length(x)
        x <- x[!is.na(x)]
        output_len <- length(x)
        warning("Found ", input_len - output_len, " NA and/or empty sequences. They were not exported since ", 
            "the FASTA format does not support missing values.")
    }
    x <- as.character(x)
    x <- vapply(x, function(x) {
        x_len <- stringr::str_length(x)
        blocks <- seq(1, x_len, by = 10)
        res <- stringr::str_sub(x, blocks, blocks - 1 + 10)
        separator <- rep(" ", length(res))
        if (x_len > 80) {
            separator[seq(8, 8 * (x_len%/%80), 8)] <- "\n"
        }
        separator[length(separator)] <- ""
        res <- stringr::str_c(res, separator, collapse = "")
        res
    }, vector("character", 1))
    fas <- stringr::str_c(">", names(x), sep = "")
    fas <- stringr::str_c(fas, x, sep = "\n", collapse = "\n\n")
    readr::write_file(fas, file, append = append)
}
<bytecode: 0x2d83e40>
<environment: namespace:bioseq>

When I use the help function for write_fasta I also DO NOT see those parameters available. Another thing is the online R documentation for write_fasta also does not mention these parameters.

Any thoughts? Using the packageVersion() function tells me I'm using bioseq v.0.1.3.

-Kenny

**Comment by fkeck** [comment]
Hi,
Yes this is normal. The "block_length_argument" and "line_length argument have been added recently and are not available on CRAN yet. If you want to use them you need to use the dev version of bioseq. You can install it using :
`remotes::install_github("fkeck/bioseq")`
