### ISSUE TITLE
warning message for `validate_seq()` doesn't respect the `type` argument

### ISSUE THREAD

**Issue by archavan** [fkeck/bioseq#17]
Thanks for this great package! The warning message in `validate_seq()`, [here](https://github.com/fkeck/bioseq/blob/cff2c5515c01dac85a2a798c3838e481055e6dda/R/checks_validation.R#L39-L41), prints `characters were converted to N` regardless of whether the `type` argument is set to `AA`, in which case the invalid characters are actually replaced by an `X` (appropriately) as can be seen in the definition of `new_aa()` [here](https://github.com/fkeck/bioseq/blob/cff2c5515c01dac85a2a798c3838e481055e6dda/R/def_aa.R#L9-L16).

This is of course a very small issue but it had me worried for some time when I read a protein fasta file with some non-standard characters and saw the message that those characters were converted to an `N` (instead of `X` as I was expecting).

**Comment by fkeck** [comment]
Thanks a lot for reporting. This should be solved now with the Github version.
